language: python
python:
  - "3.4"
  - "3.5"
install:
    - pip install coveralls
script:
    - coverage run --source pis --omit pis/test_all.py -m unittest discover -s pis && coverage report
after_success:
    - coveralls
